import { useEffect, useState } from 'react'
import Layout from '../../components/Layout'
import { supabase } from '../../lib/supabaseClient'
import { useAuth } from '../../context/AuthContext'
export default function GradesPage(){
 const {user}=useAuth(); const [students,setStudents]=useState([]),[subjects,setSubjects]=useState([]),[grades,setGrades]=useState([])
 const [form,setForm]=useState({student_id:'',subject_id:'',title:'اختبار',score:'',max_score:100})
 useEffect(()=>{load()},[])
 async function load(){const [s,sub,g]=await Promise.all([supabase.from('students').select('id, student_number, profiles(full_name), classes(name,section)').order('id'),supabase.from('subjects').select('*'),supabase.from('grades').select('*, students(profiles(full_name)), subjects(name)').order('created_at',{ascending:false})]); if(!s.error)setStudents(s.data||[]); if(!sub.error)setSubjects(sub.data||[]); if(!g.error)setGrades(g.data||[])}
 async function save(e){e.preventDefault(); const {error}=await supabase.from('grades').insert({...form,student_id:Number(form.student_id),subject_id:Number(form.subject_id),score:Number(form.score),max_score:Number(form.max_score),teacher_id:user.id}); if(error)alert(error.message); else{setForm({...form,score:''});load()}}
 return <Layout title="إدخال الدرجات"><form onSubmit={save} className="card p-4 mb-6 grid md:grid-cols-5 gap-3"><select className="input" value={form.student_id} onChange={e=>setForm({...form,student_id:e.target.value})} required><option value="">الطالب</option>{students.map(s=><option key={s.id} value={s.id}>{s.profiles?.full_name}</option>)}</select><select className="input" value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})} required><option value="">المادة</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input className="input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input className="input" type="number" placeholder="الدرجة" value={form.score} onChange={e=>setForm({...form,score:e.target.value})} required/><button className="btn btn-primary">حفظ</button></form><div className="table-wrap"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-right">الطالب</th><th className="p-3 text-right">المادة</th><th className="p-3 text-right">التقييم</th><th className="p-3 text-right">الدرجة</th></tr></thead><tbody>{grades.map(g=><tr key={g.id} className="border-t"><td className="p-3">{g.students?.profiles?.full_name}</td><td className="p-3">{g.subjects?.name}</td><td className="p-3">{g.title}</td><td className="p-3">{g.score}/{g.max_score}</td></tr>)}</tbody></table></div></Layout>
}
