import { useEffect, useState } from 'react'
import Layout from '../../components/Layout'
import { supabase } from '../../lib/supabaseClient'
import { useAuth } from '../../context/AuthContext'
export default function OnlineExamsPage(){
 const {user}=useAuth(); const [classes,setClasses]=useState([]),[subjects,setSubjects]=useState([]),[exams,setExams]=useState([]),[selected,setSelected]=useState(null),[questions,setQuestions]=useState([])
 const [form,setForm]=useState({title:'',description:'',class_id:'',subject_id:'',duration_minutes:30,total_score:100,is_published:false,allow_retake:false})
 const [q,setQ]=useState({question_text:'',question_type:'mcq',options:'',correct_answer:'',score:1})
 useEffect(()=>{load()},[])
 async function load(){const [c,s,e]=await Promise.all([supabase.from('classes').select('*'),supabase.from('subjects').select('*'),supabase.from('online_exams').select('*, classes(name), subjects(name)').order('created_at',{ascending:false})]); if(!c.error)setClasses(c.data||[]); if(!s.error)setSubjects(s.data||[]); if(!e.error)setExams(e.data||[])}
 async function save(e){e.preventDefault(); const {error}=await supabase.from('online_exams').insert({...form,class_id:Number(form.class_id),subject_id:Number(form.subject_id),duration_minutes:Number(form.duration_minutes),total_score:Number(form.total_score),teacher_id:user.id}); if(error)alert(error.message); else load()}
 async function open(ex){setSelected(ex); const {data}=await supabase.from('online_exam_questions').select('*').eq('exam_id',ex.id).order('sort_order'); setQuestions(data||[])}
 async function addQuestion(e){e.preventDefault(); const options=q.question_type==='mcq'?q.options.split('\n').map(x=>x.trim()).filter(Boolean):null; const {error}=await supabase.from('online_exam_questions').insert({exam_id:selected.id,question_text:q.question_text,question_type:q.question_type,options,correct_answer:q.correct_answer,score:Number(q.score),sort_order:questions.length+1}); if(error)alert(error.message); else{setQ({question_text:'',question_type:'mcq',options:'',correct_answer:'',score:1});open(selected)}}
 async function toggle(ex){await supabase.from('online_exams').update({is_published:!ex.is_published}).eq('id',ex.id); load()}
 return <Layout title="امتحانات أونلاين"><form onSubmit={save} className="card p-4 mb-6 grid md:grid-cols-4 gap-3"><input className="input" placeholder="عنوان الامتحان" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><select className="input" value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})} required><option value="">الصف</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="input" value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})} required><option value="">المادة</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input className="input" type="number" value={form.duration_minutes} onChange={e=>setForm({...form,duration_minutes:e.target.value})}/><label><input type="checkbox" checked={form.is_published} onChange={e=>setForm({...form,is_published:e.target.checked})}/> منشور</label><button className="btn btn-primary">إنشاء</button></form><div className="grid lg:grid-cols-2 gap-4"><div className="card p-4"><h3 className="font-black">الامتحانات</h3>{exams.map(ex=><div key={ex.id} className="border-t py-3"><b>{ex.title}</b><p>{ex.classes?.name} - {ex.subjects?.name} - {ex.is_published?'منشور':'مخفي'}</p><button onClick={()=>open(ex)} className="text-blue-600 font-bold">أسئلة</button> <button onClick={()=>toggle(ex)} className="text-green-700 font-bold">{ex.is_published?'إخفاء':'نشر'}</button></div>)}</div><div className="card p-4"><h3 className="font-black mb-3">{selected?`أسئلة ${selected.title}`:'اختر امتحان'}</h3>{selected&&<form onSubmit={addQuestion} className="space-y-2"><select className="input" value={q.question_type} onChange={e=>setQ({...q,question_type:e.target.value})}><option value="mcq">اختيار من متعدد</option><option value="true_false">صح/خطأ</option><option value="short_answer">إجابة قصيرة</option></select><textarea className="input" placeholder="السؤال" value={q.question_text} onChange={e=>setQ({...q,question_text:e.target.value})} required/>{q.question_type==='mcq'&&<textarea className="input" placeholder="الخيارات كل خيار بسطر" value={q.options} onChange={e=>setQ({...q,options:e.target.value})}/>}<input className="input" placeholder="الإجابة الصحيحة" value={q.correct_answer} onChange={e=>setQ({...q,correct_answer:e.target.value})}/><input className="input" type="number" value={q.score} onChange={e=>setQ({...q,score:e.target.value})}/><button className="btn btn-primary">إضافة سؤال</button></form>}{questions.map(x=><div key={x.id} className="border-t py-2">{x.question_text}</div>)}</div></div></Layout>
}
