import { useEffect, useState } from 'react'
import Layout from '../../components/Layout'
import { supabase } from '../../lib/supabaseClient'
import { useAuth } from '../../context/AuthContext'
export default function OnlineAssignmentsPage(){
 const {user}=useAuth(); const [classes,setClasses]=useState([]),[subjects,setSubjects]=useState([]),[assignments,setAssignments]=useState([]),[subs,setSubs]=useState([])
 const [form,setForm]=useState({class_id:'',subject_id:'',title:'',description:'',due_date:'',max_score:100})
 useEffect(()=>{load()},[])
 async function load(){const [c,s,a]=await Promise.all([supabase.from('classes').select('*'),supabase.from('subjects').select('*'),supabase.from('assignments').select('*, classes(name,section), subjects(name)').order('created_at',{ascending:false})]); if(!c.error)setClasses(c.data||[]); if(!s.error)setSubjects(s.data||[]); if(!a.error)setAssignments(a.data||[])}
 async function save(e){e.preventDefault(); const {error}=await supabase.from('assignments').insert({...form,class_id:Number(form.class_id),subject_id:Number(form.subject_id),teacher_id:user.id,is_online:true,max_score:Number(form.max_score)}); if(error)alert(error.message); else{setForm({class_id:'',subject_id:'',title:'',description:'',due_date:'',max_score:100});load()}}
 async function loadSubs(id){const {data,error}=await supabase.from('assignment_submissions').select('*, students(student_number, profiles(full_name))').eq('assignment_id',id); if(error)alert(error.message); else setSubs(data||[])}
 return <Layout title="واجبات أونلاين"><form onSubmit={save} className="card p-4 mb-6 grid md:grid-cols-3 gap-3"><select className="input" value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})} required><option value="">الصف</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="input" value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})} required><option value="">المادة</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input className="input" placeholder="العنوان" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><input className="input" type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/><textarea className="input md:col-span-2" placeholder="شرح الواجب" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="btn btn-primary">إضافة واجب</button></form><div className="grid lg:grid-cols-2 gap-4"><div className="card p-4"><h3 className="font-black mb-3">الواجبات</h3>{assignments.map(a=><div key={a.id} className="border-t py-3"><b>{a.title}</b><p className="text-sm text-slate-500">{a.classes?.name} - {a.subjects?.name}</p><button onClick={()=>loadSubs(a.id)} className="text-blue-600 font-bold">التسليمات</button></div>)}</div><div className="card p-4"><h3 className="font-black mb-3">التسليمات</h3>{subs.map(s=><div key={s.id} className="border-t py-3"><b>{s.students?.profiles?.full_name}</b><p className="whitespace-pre-wrap">{s.answer_text}</p></div>)}</div></div></Layout>
}
