import { useEffect, useState } from 'react'
import Layout from '../../components/Layout'
import { supabase } from '../../lib/supabaseClient'
import { useAuth } from '../../context/AuthContext'
export default function OnlineExamsPage(){
 const {user}=useAuth(); const [student,setStudent]=useState(null),[exams,setExams]=useState([]),[active,setActive]=useState(null),[questions,setQuestions]=useState([]),[answers,setAnswers]=useState({})
 useEffect(()=>{load()},[])
 async function load(){const {data:st}=await supabase.from('students').select('id,class_id').eq('profile_id',user.id).maybeSingle(); if(!st)return; setStudent(st); const {data}=await supabase.from('online_exams').select('*, subjects(name)').eq('class_id',st.class_id).eq('is_published',true); setExams(data||[])}
 async function start(ex){const {data}=await supabase.from('online_exam_questions').select('*').eq('exam_id',ex.id).order('sort_order'); setQuestions(data||[]); setAnswers({}); setActive(ex)}
 async function submit(){if(!confirm('تسليم الامتحان؟'))return; const {data:attempt,error}=await supabase.from('online_exam_attempts').insert({exam_id:active.id,student_id:student.id,status:'submitted',submitted_at:new Date().toISOString()}).select('*').single(); if(error)return alert(error.message); let score=0; const rows=questions.map(q=>{const ans=String(answers[q.id]||'').trim(); let correct=null,aw=0; if(q.question_type!=='short_answer'){correct=ans.toLowerCase()===String(q.correct_answer||'').trim().toLowerCase(); aw=correct?Number(q.score||0):0; score+=aw} return {attempt_id:attempt.id,question_id:q.id,answer_text:ans,is_correct:correct,score_awarded:aw}}); const {error:e2}=await supabase.from('online_exam_answers').insert(rows); if(e2)return alert(e2.message); await supabase.from('online_exam_attempts').update({auto_score:score,total_score:score}).eq('id',attempt.id); alert(`تم التسليم. العلامة التلقائية: ${score}`); setActive(null); load()}
 if(active)return <Layout title={`امتحان: ${active.title}`}><div className="space-y-4">{questions.map((q,i)=><div key={q.id} className="card p-4"><b>{i+1}. {q.question_text}</b>{q.question_type==='mcq'&&(q.options||[]).map(op=><label key={op} className="block mt-2"><input type="radio" name={'q'+q.id} onChange={()=>setAnswers({...answers,[q.id]:op})}/> {op}</label>)}{q.question_type==='true_false'&&<div><label className="block mt-2"><input type="radio" name={'q'+q.id} onChange={()=>setAnswers({...answers,[q.id]:'true'})}/> صح</label><label className="block mt-2"><input type="radio" name={'q'+q.id} onChange={()=>setAnswers({...answers,[q.id]:'false'})}/> خطأ</label></div>}{q.question_type==='short_answer'&&<textarea className="input mt-3 min-h-[100px]" onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}/>}<p className="text-sm text-slate-500 mt-2">العلامة: {q.score}</p></div>)}</div><button onClick={submit} className="btn btn-green mt-6">تسليم الامتحان</button></Layout>
 return <Layout title="امتحانات أونلاين"><div className="space-y-4">{exams.map(ex=><div key={ex.id} className="card p-4"><h3 className="font-black">{ex.title}</h3><p className="text-slate-500">{ex.subjects?.name} - {ex.duration_minutes} دقيقة</p><p>{ex.description}</p><button onClick={()=>start(ex)} className="btn btn-primary mt-3">بدء الامتحان</button></div>)}</div></Layout>
}
