import { useEffect, useState } from 'react'
import Layout from '../../components/Layout'
import { supabase } from '../../lib/supabaseClient'
import { useAuth } from '../../context/AuthContext'
export default function GradeVisibilityPage(){
 const {user}=useAuth(); const [rules,setRules]=useState([]),[classes,setClasses]=useState([]),[subjects,setSubjects]=useState([]),[students,setStudents]=useState([])
 const [form,setForm]=useState({title:'',is_visible:'true',class_id:'',subject_id:'',student_id:''})
 useEffect(()=>{load()},[])
 async function load(){const [r,c,s,st]=await Promise.all([supabase.from('grade_visibility_rules').select('*, classes(name,section), subjects(name), students(student_number, profiles(full_name))').order('created_at',{ascending:false}),supabase.from('classes').select('*'),supabase.from('subjects').select('*'),supabase.from('students').select('id, student_number, profiles(full_name)').order('id')]); if(!r.error)setRules(r.data||[]); if(!c.error)setClasses(c.data||[]); if(!s.error)setSubjects(s.data||[]); if(!st.error)setStudents(st.data||[])}
 async function save(e){e.preventDefault(); const {error}=await supabase.from('grade_visibility_rules').insert({title:form.title|| (form.is_visible==='true'?'إظهار العلامات':'إخفاء العلامات'),is_visible:form.is_visible==='true',class_id:form.class_id?Number(form.class_id):null,subject_id:form.subject_id?Number(form.subject_id):null,student_id:form.student_id?Number(form.student_id):null,created_by:user.id}); if(error)alert(error.message); else{setForm({title:'',is_visible:'true',class_id:'',subject_id:'',student_id:''});load()}}
 async function quick(v){const {error}=await supabase.from('grade_visibility_rules').insert({title:v?'إظهار كل العلامات':'إخفاء كل العلامات',is_visible:v,created_by:user.id}); if(error)alert(error.message); else load()}
 return <Layout title="إظهار/إخفاء العلامات"><div className="grid md:grid-cols-2 gap-3 mb-6"><button onClick={()=>quick(false)} className="btn btn-red p-4">إخفاء كل العلامات</button><button onClick={()=>quick(true)} className="btn btn-green p-4">إظهار كل العلامات</button></div><form onSubmit={save} className="card p-4 mb-6 grid md:grid-cols-5 gap-3"><select className="input" value={form.is_visible} onChange={e=>setForm({...form,is_visible:e.target.value})}><option value="true">إظهار</option><option value="false">إخفاء</option></select><select className="input" value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})}><option value="">كل الصفوف</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} {c.section||''}</option>)}</select><select className="input" value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})}><option value="">كل المواد</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select className="input" value={form.student_id} onChange={e=>setForm({...form,student_id:e.target.value})}><option value="">كل الطلاب</option>{students.map(s=><option key={s.id} value={s.id}>{s.profiles?.full_name}</option>)}</select><button className="btn btn-primary">إضافة قاعدة</button></form><div className="table-wrap"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-right">الحالة</th><th className="p-3 text-right">العنوان</th><th className="p-3 text-right">النطاق</th></tr></thead><tbody>{rules.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.is_visible?'إظهار':'إخفاء'}</td><td className="p-3">{r.title}</td><td className="p-3">{r.classes?.name||'كل الصفوف'} / {r.subjects?.name||'كل المواد'} / {r.students?.profiles?.full_name||'كل الطلاب'}</td></tr>)}</tbody></table></div></Layout>
}
