import { useEffect, useState } from 'react'
import Layout from '../../components/Layout'
import { supabase } from '../../lib/supabaseClient'
export default function StudentFeesPage(){
 const [students,setStudents]=useState([]),[terms,setTerms]=useState([]),[fees,setFees]=useState([])
 const [form,setForm]=useState({student_id:'',academic_term_id:'',title:'رسوم مدرسية',amount:'',due_date:''})
 useEffect(()=>{load()},[])
 async function load(){const [s,t,f]=await Promise.all([supabase.from('students').select('id, student_number, profiles(full_name)').order('id'),supabase.from('academic_terms').select('*'),supabase.from('student_fees').select('*, students(student_number, profiles(full_name)), academic_terms(name, year_label)').order('created_at',{ascending:false})]); if(!s.error)setStudents(s.data||[]); if(!t.error)setTerms(t.data||[]); if(!f.error)setFees(f.data||[])}
 async function save(e){e.preventDefault(); const {error}=await supabase.from('student_fees').insert({student_id:Number(form.student_id),academic_term_id:form.academic_term_id?Number(form.academic_term_id):null,title:form.title,amount:Number(form.amount),due_date:form.due_date||null}); if(error)alert(error.message); else{setForm({...form,amount:''});load()}}
 return <Layout title="رسوم الطلاب"><form onSubmit={save} className="card p-4 mb-6 grid md:grid-cols-5 gap-3"><select className="input" value={form.student_id} onChange={e=>setForm({...form,student_id:e.target.value})} required><option value="">الطالب</option>{students.map(s=><option key={s.id} value={s.id}>{s.profiles?.full_name} - {s.student_number}</option>)}</select><select className="input" value={form.academic_term_id} onChange={e=>setForm({...form,academic_term_id:e.target.value})}><option value="">الفصل</option>{terms.map(t=><option key={t.id} value={t.id}>{t.name} - {t.year_label}</option>)}</select><input className="input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input className="input" type="number" step="0.01" placeholder="المبلغ" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/><button className="btn btn-primary">إضافة رسم</button></form><div className="table-wrap"><table className="w-full text-sm min-w-[700px]"><thead className="bg-slate-50"><tr><th className="p-3 text-right">الطالب</th><th className="p-3 text-right">العنوان</th><th className="p-3 text-right">المبلغ</th><th className="p-3 text-right">الفصل</th></tr></thead><tbody>{fees.map(f=><tr key={f.id} className="border-t"><td className="p-3">{f.students?.profiles?.full_name}</td><td className="p-3">{f.title}</td><td className="p-3">{f.amount}</td><td className="p-3">{f.academic_terms?.name || '-'}</td></tr>)}</tbody></table></div></Layout>
}
