import { useEffect, useState } from 'react'
import Layout from '../../components/Layout'
import { supabase } from '../../lib/supabaseClient'
function receipt(){const d=new Date();return `RC-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}-${Date.now().toString().slice(-5)}`}
export default function StudentPaymentsPage(){
 const [students,setStudents]=useState([]),[terms,setTerms]=useState([]),[payments,setPayments]=useState([])
 const [form,setForm]=useState({student_id:'',academic_term_id:'',amount:'',payment_date:new Date().toISOString().slice(0,10),method:'cash',receipt_no:receipt(),note:''})
 useEffect(()=>{load()},[])
 async function load(){const [s,t,p]=await Promise.all([supabase.from('students').select('id, student_number, profiles(full_name)').order('id'),supabase.from('academic_terms').select('*'),supabase.from('student_payments').select('*, students(student_number, profiles(full_name))').order('created_at',{ascending:false})]); if(!s.error)setStudents(s.data||[]); if(!t.error)setTerms(t.data||[]); if(!p.error)setPayments(p.data||[])}
 async function save(e){e.preventDefault(); const {error}=await supabase.from('student_payments').insert({...form,student_id:Number(form.student_id),academic_term_id:form.academic_term_id?Number(form.academic_term_id):null,amount:Number(form.amount)}); if(error)alert(error.message); else{alert('تم تسجيل الدفعة');setForm({...form,amount:'',receipt_no:receipt()});load()}}
 function print(p){const html=`<html dir="rtl"><body style="font-family:Arial;padding:30px"><div style="border:1px solid #222;padding:20px;border-radius:12px"><h1 style="text-align:center">سند قبض</h1><p>رقم السند: ${p.receipt_no}</p><p>الطالب: ${p.students?.profiles?.full_name||''}</p><p>المبلغ: ${p.amount}</p><p>التاريخ: ${p.payment_date}</p><br/><p>توقيع المحاسب: ____________</p></div><script>window.print()</script></body></html>`; const win=window.open('','_blank'); win.document.write(html); win.document.close()}
 return <Layout title="دفعات الطلاب"><form onSubmit={save} className="card p-4 mb-6 grid md:grid-cols-4 gap-3"><select className="input" value={form.student_id} onChange={e=>setForm({...form,student_id:e.target.value})} required><option value="">الطالب</option>{students.map(s=><option key={s.id} value={s.id}>{s.profiles?.full_name}</option>)}</select><input className="input" type="number" step="0.01" placeholder="المبلغ" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/><input className="input" value={form.receipt_no} onChange={e=>setForm({...form,receipt_no:e.target.value})}/><button className="btn btn-primary">تسجيل دفعة</button></form><div className="table-wrap"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-right">السند</th><th className="p-3 text-right">الطالب</th><th className="p-3 text-right">المبلغ</th><th className="p-3 text-right">إجراء</th></tr></thead><tbody>{payments.map(p=><tr key={p.id} className="border-t"><td className="p-3">{p.receipt_no}</td><td className="p-3">{p.students?.profiles?.full_name}</td><td className="p-3">{p.amount}</td><td className="p-3"><button onClick={()=>print(p)} className="text-blue-600 font-bold">طباعة</button></td></tr>)}</tbody></table></div></Layout>
}
